# /etc/pacman.conf
# MAD EL OS - Custom Arch Linux with Thai Language Support

[options]
Architecture = auto
HoldPkg = pacman glibc
SigLevel = required database-optional
LocalFileSigLevel = optional
XferCommand = /usr/bin/curl --fail --user-agent "pacman/6.0" -SLO %u
ParallelDownloads = 5
VerbosePkgLists = true
CleanMethod = 2

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
