title    MAD EL OS - Thai Edition
linux    /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisodevice=/dev/disk/by-label/%ARCHISO_LABEL% keymap=th layout=th cow_spacesize=2G
